In [3]:
import numpy as np

In [4]:
print (np.cos(np.pi))
print (np.sqrt(1.21))
print (np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [5]:
vec = np.array([1,2,3])
print (vec)
mat = np.array([[1,4,6],[4,6,9],[5,2,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 4 6]
 [4 6 9]
 [5 2 9]]

[[1 4 5]
 [4 6 2]
 [6 9 9]]


In [6]:
vec2=np.arange(0,9)
print(vec2)
vec3=np.arange(3,24,3)
print(vec3)

[0 1 2 3 4 5 6 7 8]
[ 3  6  9 12 15 18 21]


In [7]:
vec4 = np.linspace(0,5,14)
print (vec4)
print ('')
print (vec4.reshape(7,2))
print (vec4)

[0.         0.38461538 0.76923077 1.15384615 1.53846154 1.92307692
 2.30769231 2.69230769 3.07692308 3.46153846 3.84615385 4.23076923
 4.61538462 5.        ]

[[0.         0.38461538]
 [0.76923077 1.15384615]
 [1.53846154 1.92307692]
 [2.30769231 2.69230769]
 [3.07692308 3.46153846]
 [3.84615385 4.23076923]
 [4.61538462 5.        ]]
[0.         0.38461538 0.76923077 1.15384615 1.53846154 1.92307692
 2.30769231 2.69230769 3.07692308 3.46153846 3.84615385 4.23076923
 4.61538462 5.        ]


In [8]:
mat2 = np.zeros([5,3])
print (mat2)
mat3 = np.ones((3,4))
print('')
print(mat3)
mat4=np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print('')
print(vec6)
print('')
print(vec5+vec6)
print('')
print(vec5*vec6)
print('')
print(vec6-vec5)
print('')
print(1/vec5)
print('')
print(np.sqrt(vec6))

[1 2 3 4 5]

[3 4 5 6 7]

[ 4  6  8 10 12]

[ 3  8 15 24 35]

[2 2 2 2 2]

[1.         0.5        0.33333333 0.25       0.2       ]

[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [10]:
print(mat)
print(vec)
matm=np.matmul(mat,vec)
print(matm)

[[1 4 6]
 [4 6 9]
 [5 2 9]]
[1 2 3]
[27 43 36]


In [11]:
sol=np.linalg.solve(mat,matm)
print(sol)
inv=np.linalg.inv(mat)
print(inv)

[1. 2. 3.]
[[-6.00000000e-01  4.00000000e-01  4.44089210e-17]
 [-1.50000000e-01  3.50000000e-01 -2.50000000e-01]
 [ 3.66666667e-01 -3.00000000e-01  1.66666667e-01]]


In [12]:
vec7=np.array(['a','b','d','d','B',4,7])
print(vec7)
print(np.unique(vec7))

['a' 'b' 'd' 'd' 'B' '4' '7']
['4' '7' 'B' 'a' 'b' 'd']


In [13]:
rand_1=np.random.rand(5,5)
print(rand_1)
rand_2=np.random.randn(5,5)
print('')
print(rand_2)

[[0.72522627 0.80435718 0.10152988 0.57036098 0.10790387]
 [0.98096743 0.70499901 0.69129787 0.25782302 0.49932769]
 [0.57173111 0.48036873 0.41931878 0.95930505 0.31042164]
 [0.48377197 0.49572261 0.73700943 0.32231703 0.45674701]
 [0.55921296 0.1219428  0.18391368 0.09014955 0.20508563]]

[[ 1.02991107  0.78443692 -0.4775698  -0.29420962 -0.57288412]
 [ 0.14439192 -1.5555518  -0.24510512 -0.8057535   0.54531223]
 [-0.12951552 -1.9452352   0.25046411 -0.31056225  0.78948366]
 [-0.72584434 -0.02308601 -0.40235852  0.71824433  0.07399059]
 [-0.92577589  0.24900832  1.13918067  0.18374777 -1.56095882]]


In [14]:
print(np.mean(rand_1))
print(np.std(rand_2))

0.4736324473436529
0.7895757040214918


In [15]:
print(np.min(rand_1))
print(np.max(rand_2))

0.09014954663741837
1.139180667201454


In [18]:
print(rand_1)

[[0.72522627 0.80435718 0.10152988 0.57036098 0.10790387]
 [0.98096743 0.70499901 0.69129787 0.25782302 0.49932769]
 [0.57173111 0.48036873 0.41931878 0.95930505 0.31042164]
 [0.48377197 0.49572261 0.73700943 0.32231703 0.45674701]
 [0.55921296 0.1219428  0.18391368 0.09014955 0.20508563]]


In [17]:
np.save('saved_file',rand_2)