In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)

In [3]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print (myseries2)

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64
0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


In [4]:
print (myseries1[2])

1.7


In [5]:
mylabels=['first','second','third','fourth']
myser3 = pd.Series(data=mylist,index=mylabels)
print (myser3)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [6]:
myser4=pd.Series(mylist,mylabels)
print (myser4)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [7]:
print(myser4['second'])

6.1


In [8]:
myser5=pd.Series([5.1,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myser5)
print('')
print(myser5+myser4)

first     5.1
third     1.1
fourth    8.8
fifth     1.6
dtype: float64

fifth       NaN
first      10.5
fourth    108.6
second      NaN
third       2.8
dtype: float64


In [9]:
df1 = pd.concat([myser4,myser5],axis=1,sort=False)
df1

0    1
first    5.4  5.1
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [10]:
df2=pd.DataFrame(np.random.randn(5,5))
df2

0         1         2         3         4
0 -1.672275 -0.395785 -0.706051  0.701318  1.346434
1 -0.430318 -1.452885  0.931198 -1.242358 -0.102917
2 -1.922400  1.096853  1.230148  1.500012 -0.859773
3  1.078015 -1.082227  0.437465 -0.057018  0.818548
4 -0.787540  0.555942 -0.284846  2.290923 -0.024729

In [11]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [12]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
print(demo_matrix)
demo_matrix[:, (1,2)]

[[13 35 74 48]
 [23 37 37 38]
 [73 39 93 39]]


array([[35, 74],
       [37, 37],
       [39, 93]])

In [13]:
test_array = [10, 11.5, 12, 13.5, 14,15]   
test_array[2:3]

[12]

In [15]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [16]:
demo_array=np.arange(0,10)
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.max(demo_array)

9

In [23]:
football=[1,2,3,4]
ary=np.array(football)
ary

array([1, 2, 3, 4])

In [24]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [27]:
df_data = {'index': ['0', '1'],
'set1': ['A', 'B']}
df=pd.DataFrame(df_data)
print(df)

  index set1
0     0    A
1     1    B


In [29]:
new=["P","Q"]
df['set2']=new
df

index set1 set2
0     0    A    P
1     1    B    Q

In [30]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

In [31]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [33]:
!pip install pandas-profiling==2.9.0